version: '3'

services:
  ncr_postgre:
    image: postgres:latest
    container_name: pegasas_fast
    restart: always
    environment:
      POSTGRES_PASSWORD: '12345'
    ports:
      - '5432:5432'
    volumes:
      - ./sql_fast.sql:/docker-entrypoint-initdb.d/sql_fast.sql
      - pgdatavolume2:/var/lib/postgresql/data

  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"

volumes:
    pgdatavolume2:


